### PR TITLE
Issue 101 conf fp over time

### PR DESCRIPTION
**Pull request by shukon**
main changes: adding four choices for configurator footprints (`--cfp_time_slider_type`):
- off: no investigation over time, only interactive plot
- static: only `.png`s (to click through)
- prerender: big file, fast change between quantiles (but possibly long loading times, I cannot run any big example right now, because of login-problems on the cluster ... @AndreBiedenkapp would you mind running `prerender` against `online` so we can check whether there is a significant difference?
- online: smaller file, change between quantiles needs updates in data and takes longer (not sure until what size of data it is feasible

another new argument is `cfp_number_quantiles` (self-explanatory?)
currently quantiles are on linear-scale, is that good or do we want log-scale?

smaller changes:
many changes in docs, logs, imports and arguments for configurator_footprint...

### CODE REVIEW

**Comment by shukon** [comment]
@AndreBiedenkapp What was command in the cmd-line? And could you send me the `<output>/debug/debug.log`?

**Comment by AndreBiedenkapp** [comment]
@shukon I just send you all 4 runs

**Comment by AndreBiedenkapp** [comment]
@shukon is this ready to be tested/reviewed again?

**Comment by shukon** [comment]
@AndreBiedenkapp well - I fixed a lot of bugs, but I couldn't reproduce yours. Maybe you can try again? I improved the logs a lot as well, so this time they will hopefully give more information.

**Comment by AndreBiedenkapp** [comment]
Okay. I'll have a look today

**Comment by AndreBiedenkapp** [comment]
@shukon One thing I noticed already is that a ton of run_1.OLD folders are created in the working directory. Do you have any idea what changed in SMAC that all these run_1.OLD folders are created?

**Comment by shukon** [comment]
@AndreBiedenkapp not really, but I this doen't happen on smac's dev-branch (at least not for me) so I'd assume it's already fixed.
Currently, the "max_plot"-argument reduces the number of configurations to use for the config-plot to 1500. Do you think this is **a)** a good idea and **b)** should be configurable via cmd-line?

**Comment by AndreBiedenkapp** [comment]
Oh yes. On Meta I was working with SMACs Master-branch
a) Yes b) Yes.
But it should also depend on the strategy shouldn't it? If it is static then all configurations could be plotted right?

**Comment by AndreBiedenkapp** [comment]
It didn't crash this time. I'll send you the results

**Comment by shukon** [comment]
@AndreBiedenkapp the main problem I was after when reducing the number of configurations was the `MemoryError` as a result from too large distance-arrays for the MDS. I will see how to solve this.

**Pull request merged**
