### PR TITLE
ADD random/local in conf-footprint, MAINT rename conf_viz

### PR DESCRIPTION
**Pull request by shukon**
If available, plot random and local origined configurations in different colors. Otherwise print only incumbents different. To that end, restructured the plot-function in ConfiguratorFootprint.
Also renamed conf_viz to ConfiguratorFootprint.
Example:

configurator_footprint

### CODE REVIEW

**Comment by AndreBiedenkapp** [comment]
This looks awesome!
On suggesting though. Instead of coloring the points differently it might be better to use different shapes (I.e. x=local, o=random, diamond=[final]incumbent, square=default)
This leaves more room to play around with the footprints (e.g. not coloring the background but the dots according to performance predictions).

**Comment by AndreBiedenkapp** [comment]
It would also be interesting to see if an incumbent was obtained by random or local search (using the same shapes but highlighting them by color).
This was just a quick idea. Maybe you have a better idea in mind @shukon.

**Comment by shukon** [comment]
I forgot all about the shapes, thank you for reminding me. So the problem now is that the default and final incumbent in my (toy-)example-runs are very small. I don't expect this to change with more realistic examples. Should we increase the sizes for those two, so they don't follow the same proportions as the rest of the dots but can be easily found?
Below some examples with and without contour-plotting.
With contour
Without contour

**Comment by AndreBiedenkapp** [comment]
I see what you mean.
You could mess around with https://github.com/automl/CAVE/blob/4f571c1f3ba5a978daa70c5245f46363e6c97c74/cave/plot/configurator_footprint.py#L367-L368
And allow points to be larger than 50.
However it seems that different shapes scale differently in pyplot. So your suggestion to highlight the incumbent and default by larger sizes seems reasonable.

**Comment by AndreBiedenkapp** [comment]
As for the second plot without the contour, the configurations then should get the color the contour plot showed at that location.

**Comment by shukon** [comment]
continued in #123

**Pull request closed without merging**
