### PR TITLE
Multi parallel plots

### PR DESCRIPTION
**Pull request by AndreBiedenkapp**
Working on making the parallel plots more informative.
Based on suggestions by @shukon to uniformly sample the configurations to plot and also to put the colorscheme on log-scale.

Difference in logarithmic sampling and uniform sampling:
logarithmic
parallel_coordinates_999

uniform
parallel_coordinates_uniform_1000

As you can see, uniform sampling is not advantageous if there is one bad configuration that "dominates" the color spectrum.

Difference for color scheme (on a much smaller example):
logarithmic
parallel_coordinates_unlogged78

uniform
parallel_coordinates_unlogged_c78

Currently, all versions of the plot are generated, however the plot with logarithmic sampling of the configurations to plot, as well as logarithmic color-scheme is linked in the report.

In my mind, logarithmic-logarithmic is the way to go to make the parallel plots as informative as possible.

### CODE REVIEW

**Comment by AndreBiedenkapp** [comment]
Instead of log-transforming the colors, the performances are now log-transformed.

**Comment by AndreBiedenkapp** [comment]
The latest iteration now plots the best and worst configurations in the foreground and everything that is somewhere in the middle is pushed further to the background. The alpha level of the "mediocre" configurations is fixed to .6 to avoid cluttering of the plot.
Further the 5 best configurations and 5 worst configurations are highlighted with a very small border around them. This should help with identifying patterns, i.e. all worst performing ones choose one value vs all best performing ones a different value.

Example plot (again on the very small cave example, with the parameters ordered by fANOVA importance):
parallel_coordinates_log_cost78

As you can see, for the most important parameter, all the worst performing configurations are set to 0.
@shukon, @mlindauer do you think that these changes suffice to make the plot(s) more interpretable/intuitive to understand?

**Comment by mlindauer** [comment]
That looks much better. Of course, it would be interesting to see the plot for the data used in our paper but I I have hope that it should be fine now.

**Comment by shukon** [comment]
Looks a lot better, thanks!

**Pull request merged**
