### PR TITLE
Issue 56 expand stat tests on metrics

### PR DESCRIPTION
**Pull request by shukon**
use SMACs cost-aggregation per instance, add p-values to performance table for all three metrics
this PR will have to wait until SMACs dev is pulled in master...

### CODE REVIEW

**Comment by AndreBiedenkapp** [comment]
@shukon As Travis is failing I wont review yet right or do you want a review already?

**Comment by shukon** [comment]
@AndreBiedenkapp  it's something that will work with SMACs dev-branch but I'd suppose to wait until dev is pulled into master on SMAC's side (or well, is that planned anytime soon? otherwise I could also remodel to fit with master, but this is more elegant).

**Comment by AndreBiedenkapp** [comment]
@shukon Thanks for the info. I'll wait then

**Comment by shukon** [comment]
So the main change here is that the p-value of the permutation-test is now not located in overview, but for each metric in the performance table. @AndreBiedenkapp I made it compatible with SMAC's master again, because this would be nice to have for next week I think. Do you want to review?

**Pull request merged**
